name: "dependency-track"

services:
  apiserver:
    image: dependencytrack/apiserver:latest
    environment:
      # Speed up password hashing for faster initial login (default is 14 rounds).
      ALPINE_BCRYPT_ROUNDS: "4"
      TELEMETRY_SUBMISSION_ENABLED_DEFAULT: "false"
    ports:
    - "127.0.0.1:8080:8080"
    volumes:
    - "apiserver-data:/data"
    restart: unless-stopped

  frontend:
    image: dependencytrack/frontend:latest
    environment:
      API_BASE_URL: "http://localhost:8080"
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

volumes:
  apiserver-data: { }