version: '3'
name: "dependency-track-test"

services:
  apiserver:
    container_name: dtrack-apiserver
    image: dependencytrack/apiserver:snapshot
    environment:
      ALPINE_BCRYPT_ROUNDS: "4"
      TELEMETRY_SUBMISSION_ENABLED_DEFAULT: "false"
      ALPINE_DATABASE_MODE: "embedded"
    ports:
      - "8080"
    volumes:
      - "./dtrack-data/.dependency-track:/data/.dependency-track"
    restart: unless-stopped
  frontend:
    container_name: dtrack-frontend
    image: dependencytrack/frontend:snapshot
    environment:
      API_BASE_URL: "https://localhost:8080"
    ports:
      - "8081"
    restart: unless-stopped
  nginx:
    image: nginx
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./certs:/etc/ssl/dtrack
    restart: unless-stopped
    depends_on:
      - apiserver
      - frontend