services:
  apiserver:
    image: dependencytrack/apiserver:${DTRACK_VERSION:-snapshot}
    environment:
      ALPINE_BCRYPT_ROUNDS: "4"
      TELEMETRY_SUBMISSION_ENABLED_DEFAULT: "false"
      ALPINE_DATABASE_MODE: "in_memory"
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_DIR:-.}/dtrack-data:/data
    user: "1000:1000"  # Set user:group to match host permissions
    restart: unless-stopped