services:
  apiserver:
    image: dependencytrack/apiserver:${DTRACK_VERSION:-snapshot}
    environment:
      ALPINE_BCRYPT_ROUNDS: "4"
      TELEMETRY_SUBMISSION_ENABLED_DEFAULT: "false"
      ALPINE_DATABASE_MODE: "in_memory"
    ports:
      - "8080:8080"
    volumes:
      - "./dtrack-data/.dependency-track:/data/.dependency-track"
    restart: unless-stopped